FROM node:18-alpine
# The /app directory should act as the main application directory
WORKDIR /app
# Copy all files
COPY . .
# RUN npm install
RUN npm install
#RUN npm build
RUN npm run build
EXPOSE 5173
# Start the app using serve command
CMD ["npm", "run", "dev"]